import { describe, it, expect } from "vitest";
import { generateDts } from "../generate-dts.js";

function simpleMap(names: string[]): Map<string, string> {
  return new Map(names.map((n) => [n, n]));
}

describe("generateDts", () => {
  it("generates declarations for simple class names", () => {
    const result = generateDts({
      exportNames: ["container", "header"],
      exportToOriginal: simpleMap(["container", "header"]),
      exportMode: "both",
    });

    expect(result).toContain("declare const container: string;");
    expect(result).toContain("declare const header: string;");
    expect(result).toContain("export {");
    expect(result).toContain("export default");
  });

  it("handles named export mode", () => {
    const result = generateDts({
      exportNames: ["title"],
      exportToOriginal: simpleMap(["title"]),
      exportMode: "named",
    });

    expect(result).toContain("export {");
    expect(result).not.toContain("export default");
  });

  it("handles default export mode", () => {
    const result = generateDts({
      exportNames: ["title"],
      exportToOriginal: simpleMap(["title"]),
      exportMode: "default",
    });

    expect(result).not.toContain("export {");
    expect(result).toContain("export default");
  });

  it("handles both export mode", () => {
    const result = generateDts({
      exportNames: ["title"],
      exportToOriginal: simpleMap(["title"]),
      exportMode: "both",
    });

    expect(result).toContain("export {");
    expect(result).toContain("export default");
  });

  it("sanitizes class names with dashes", () => {
    const result = generateDts({
      exportNames: ["my-class"],
      exportToOriginal: simpleMap(["my-class"]),
      exportMode: "both",
    });

    expect(result).toContain("declare const myClass: string;");
    expect(result).toContain('myClass as "my-class"');
  });

  it("handles camelCase localsConvention exports", () => {
    const exportToOriginal = new Map([
      ["input-container", "input-container"],
      ["inputContainer", "input-container"],
    ]);

    const result = generateDts({
      exportNames: ["input-container", "inputContainer"],
      exportToOriginal,
      exportMode: "named",
    });

    expect(result).toContain("declare const inputContainer: string;");
  });

  it("handles camelCaseOnly exports with source map to original", () => {
    const exportToOriginal = new Map([["inputContainer", "input-container"]]);
    const classPositions = new Map([["input-container", { line: 3, column: 1 }]]);

    const result = generateDts({
      exportNames: ["inputContainer"],
      exportToOriginal,
      exportMode: "named",
      sourceMapOptions: {
        classPositions,
        sourceFileName: "/project/styles.module.css",
      },
    });

    expect(result).toContain("declare const inputContainer: string;");
    expect(result).toContain("sourceMappingURL");
  });

  it("returns header only for empty export names", () => {
    const result = generateDts({
      exportNames: [],
      exportToOriginal: new Map(),
      exportMode: "both",
    });

    expect(result).toContain("// Generated by vite-css-module-types");
    expect(result).not.toContain("declare const");
    expect(result).not.toContain("export");
  });

  it("includes header comments", () => {
    const result = generateDts({
      exportNames: ["a"],
      exportToOriginal: simpleMap(["a"]),
      exportMode: "both",
    });

    expect(result).toContain("/* eslint-disable */");
    expect(result).toContain("/* prettier-ignore */");
    expect(result).toContain("// @ts-nocheck");
    expect(result).toContain("// Generated by vite-css-module-types");
  });

  it("deduplicates variables that sanitize to the same name", () => {
    const result = generateDts({
      exportNames: ["my-class", "myClass"],
      exportToOriginal: new Map([
        ["my-class", "my-class"],
        ["myClass", "my-class"],
      ]),
      exportMode: "named",
    });

    const matches = result.match(/declare const myClass: string;/g);
    expect(matches).toHaveLength(1);
  });

  it("appends source map when sourceMapOptions provided", () => {
    const classPositions = new Map([["title", { line: 3, column: 1 }]]);

    const result = generateDts({
      exportNames: ["title"],
      exportToOriginal: simpleMap(["title"]),
      exportMode: "named",
      sourceMapOptions: {
        classPositions,
        sourceFileName: "/project/styles.module.css",
      },
    });

    expect(result).toContain("//# sourceMappingURL=data:application/json;charset=utf-8;base64,");
  });

  it("omits source map when sourceMapOptions not provided", () => {
    const result = generateDts({
      exportNames: ["title"],
      exportToOriginal: simpleMap(["title"]),
      exportMode: "named",
    });

    expect(result).not.toContain("sourceMappingURL");
  });
});
