import { makeLegalIdentifier } from "./utils.js";
import { buildDtsSourceMap, type DtsLine } from "./generate-sourcemap.js";
import type { ClassPosition } from "./types.js";

export type ExportMode = "named" | "default" | "both";

const HEADER_LINES = [
  "/* eslint-disable */",
  "/* oxlint-disable */",
  "// biome-ignore-all lint: generated CSS module types, do not edit",
  "// @ts-nocheck",
  "// Generated by vite-css-module-types",
  "",
];

const HEADER_LINE_COUNT = HEADER_LINES.length;
const DECLARE_CONST_PREFIX_LENGTH = "declare const ".length;

interface GenerateDtsOptions {
  /** Export names (after localsConvention transformation) */
  exportNames: string[];
  /** Maps each export name back to its original CSS class name (for source maps) */
  exportToOriginal: Map<string, string>;
  exportMode: ExportMode;
  sourceMapOptions?: {
    classPositions: Map<string, ClassPosition>;
    sourceFileName: string;
  };
}

/** Generates .d.ts content with optional inline source map for Go-to-Definition. */
export function generateDts(options: GenerateDtsOptions): string {
  const { exportNames, exportToOriginal, exportMode, sourceMapOptions } = options;

  if (exportNames.length === 0) {
    return HEADER_LINES.join("\n") + "\n";
  }

  const lines: DtsLine[] = HEADER_LINES.map((text) => ({ text }));
  const declaredVars = new Set<string>();
  const variableEntries: { varName: string; exportName: string; cssClassName: string }[] = [];

  for (const exportName of exportNames) {
    const varName = makeLegalIdentifier(exportName);
    const cssClassName = exportToOriginal.get(exportName) ?? exportName;
    variableEntries.push({ varName, exportName, cssClassName });

    if (!declaredVars.has(varName)) {
      declaredVars.add(varName);
      lines.push({
        text: `declare const ${varName}: string;`,
        mapping: {
          className: cssClassName,
          column: DECLARE_CONST_PREFIX_LENGTH,
        },
      });
    }
  }

  const emitNamed = exportMode === "named" || exportMode === "both";
  const emitDefault = exportMode === "default" || exportMode === "both";

  if (emitNamed && variableEntries.length > 0) {
    lines.push({ text: "" });

    const namedEntries: { text: string; cssClassName: string }[] = [];
    for (const { varName, exportName, cssClassName } of variableEntries) {
      if (emitDefault && exportName === "default") continue;
      const text = varName === exportName ? `\t${varName}` : `\t${varName} as "${exportName}"`;
      namedEntries.push({ text, cssClassName });
    }

    if (namedEntries.length > 0) {
      lines.push({ text: "export {" });
      for (const entry of namedEntries) {
        lines.push({
          text: entry.text + ",",
          mapping: { className: entry.cssClassName, column: 1 },
        });
      }
      lines.push({ text: "};" });
    }
  }

  if (emitDefault) {
    lines.push({ text: "" });

    lines.push({ text: "declare const __default_export__: {" });
    for (const { varName, exportName, cssClassName } of variableEntries) {
      const key = varName === exportName ? varName : `"${exportName}"`;
      lines.push({
        text: `\t${key}: typeof ${varName};`,
        mapping: { className: cssClassName, column: 1 },
      });
    }
    lines.push({ text: "};" });
    lines.push({ text: "export default __default_export__;" });
  }

  let content = lines.map((l) => l.text).join("\n") + "\n";

  if (sourceMapOptions) {
    const sourceMapComment = buildDtsSourceMap({
      dtsLines: lines,
      classPositions: sourceMapOptions.classPositions,
      sourceFileName: sourceMapOptions.sourceFileName,
      headerLineCount: HEADER_LINE_COUNT,
    });
    content += sourceMapComment + "\n";
  }

  return content;
}
